### PR TITLE
Add support for Docker container

### PR DESCRIPTION
**Pull request by daanbosch**
Add support for running the ProxLB tool in a Docker container

### CODE REVIEW

**Comment by gyptazy** [comment]
Hey @daanbosch,

thanks for your efforts and your contribution! Works fine, approved & merged.

Also created an image and pushed in to my registry:
* cr.gyptazy.ch/proxlb/proxlb:v0.9.9
* cr.gyptazy.ch/proxlb/proxlb:latest

Details:
```
{
    "Name": "cr.gyptazy.ch/proxlb/proxlb",
    "Digest": "sha256:576997756c5c36babe2fe5ed1ae5f42b1d593bb2d6cb8f347cfea52f4f84f5e0",
    "RepoTags": [
        "latest",
        "v0.9.9"
    ],
    "Created": "2024-07-10T10:38:55.496022038Z",
    "DockerVersion": "",
    "Labels": {
        "org.label-schema.description": "ProxLB - Rebalance VM workloads across nodes in a Proxmox cluster.",
        "org.label-schema.schema-version": "0.9",
        "org.label-schema.url": "https://github.com/gyptazy/ProxLB"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:e9aef93137af6e967e7242f3b3c8ecd8e6f571d1e6fdd9e72db0befeeae3cf13",
        "sha256:29f004a5324022e2060858b8d057d11e4b3f0c97c1ed2bbc9c80525a329054a4",
        "sha256:33f90c7b2b7713f27685cfcff85093b1fd9a98c692f8d5a085d4e27af8073c94",
        "sha256:97698c7dc94175d143152f6cc6f435cc8afe5deedd234caa7b0691885a980c2f",
        "sha256:a91cfb92746e22fec41bea77e8b2984dad8bd66479920aeae802fae8aeb226d6",
        "sha256:7236a61da225617e85a273d1ad3826579c7c83359b02b0e4a88f8ea6fb31191b",
        "sha256:3622a33f3f4858dedb4ef6aa5c692379005b540fb6471a1500ec07747fc103a8"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "DEBIAN_FRONTEND=noninteractive"
    ]
}
```

Cheers,
gyptazy

**Review by gyptazy — APPROVED** [review]
LGTM

**Comment by daanbosch** [comment]
Hi @gyptazy,
Thank you for reviewing and merging! A public Docker image in a registry is also a great addition, thank for pushing it.

**Comment by gyptazy** [comment]
Note: Added missing changelog file and mention author @daanbosch:
https://github.com/gyptazy/ProxLB/blob/main/.changelogs/1.0.0/10_add_container_support.yml

**Pull request merged**
